### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#1]
As staff, I want to allow new volunteers & coordinator to sign up in the system, so that we can start the process of background checks and other documentation.

**Comment by benjaminwood** [comment]
:tada: I've implemented the nuts and bolts of (generic) user registration and sign-in. Nothing regarding the specifics of staff, volunteers, or coordinators has been implemented yet. But this is the basis for building those roles in the system.

I've deployed the app to heroku which is a web-application hosting platform that offers limit usage for free. You can try it now at: https://omd-scheduler.herokuapp.com

Note that the UI is very minimal and no effort has been made to style anything yet. That will come in time. :smile:

**Comment by SarahOMD** [comment]
Yes to all of that.  The only thing I would change is to name the Coordinator "Volunteer Coordinator".  It's what we use internally, and we need to stay consistent!  I'm attaching our Volunteer Agreement/Registration Packet so you can see what sorts of questions we ask up front.
[Amended-Vol Agmt Packet Instructions.pdf](https://github.com/OfficeMomsandDads/scheduler/files/2611760/Amended-Vol.Agmt.Packet.Instructions.pdf)

**Comment by benjaminwood** [comment]
Thanks! Per our phone conversation today we're planning to collect the first page of basic information from the user when they accept the invite. From there they will be 'pending activation' until OMD staff/volunteer coordinators walk them through the rest of the registration process (signing forms, etc).
