### ISSUE TITLE
Organizational structure

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#10]
@SarahOMD I believe we've identified the following as the organizational structure in our previous discussions. Can you confirm this is correct?

1. State
1. County
1. Office

Also: coordinators & volunteers can be associated with multiple offices, correct? Can social workers?

My feeling is that at least one office assignment should be required at the time that the user is invited, vs waiting for the user to input that information when the accept the invitation. What do you think?

**Comment by SarahOMD** [comment]
@benjaminwood Let's add "Region" to that list, under State.  That's not a mandatory field, but Idaho references regions a lot, so I'd like to have it available.  

Correct.  VC's and Volunteers can be associated with multiple offices, but social workers are not.

Yes, an office assignment should be a required field.

**Comment by benjaminwood** [comment]
Cool, thanks for following up.

How would region be used? I'm not against it, but adding an optional component that not all states have adds complexity to the system. So, we want to ensure that it has a specific use-case and that if we go ahead with implementing it, we implement it the right way for that use-case.

**Comment by benjaminwood** [comment]
@SarahOMD can you provide a list of regions for Washington & Idaho to get us started?

**Comment by SarahOMD** [comment]
See attached document for a list of child welfare offices per region, per state:
[Office Titles by Regions (WA and ID).docx](https://github.com/OfficeMomsandDads/scheduler/files/2677909/Office.Titles.by.Regions.WA.and.ID.docx)

**Comment by benjaminwood** [comment]
This issue is completed, though we still need the Office information from @SarahOMD if we're going to import it.

I'm going to close this out. @SarahOMD you can send us the office information via slack or open a new issue here on github (either way works!).
