### ISSUE TITLE
Adjusting shifts retroactively

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#103]
Per our phone discussion...
It would be helpful if the VC has the power to retroactively adjust shift data (duration, volunteers assigned, number of kids served, and the date) to reflect shifts that may have gone differently than what was recorded using the app, without the use of notifications.  This will help ensure accurate data collection with minimal disruption.

**Comment by sarahwicks** [comment]
I was going to enter a ticket about this issue too. Today, the social worker requested 9-4. The volunteer claimed 10-11 but had her time zone incorrect, so it showed up as claiming 9-10. She didn't show up until 10, so now it looks like an hour was served when it wasn't, which leads to inaccurate reporting. We need the ability to edit shifts once they're complete.

**Comment by benjaminwood** [comment]
I believe this issue should be superseded by/combined with #192.
