### ISSUE TITLE
Sickly Felons :-)

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#114]
Hi Guys, the ladies making the training manual had the following feedback:

This is the image that Darcy was talking about. It makes you pick both that you have a medical condition and that you are a felon, whether you do or not. It is a required field, so it doesn't allow you to submit the form without these being selected. 
![IMG_1054](https://user-images.githubusercontent.com/43186440/55414936-ede47e80-5520-11e9-8ff8-2b3de3931a8c.PNG)

**Comment by nvick** [comment]
Ref #112
