### ISSUE TITLE
Blockout times

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#115]
Another item from the the gal working on the manual:

If people need to add a blockout for just the morning or afternoon (i.e. Tuesday morning) the app doesn't allow you to select a date at all. It just stays on the date you are currently on.

Thanks

**Comment by nvick** [comment]
![image](https://user-images.githubusercontent.com/327614/55415340-b4604300-5521-11e9-96c7-0999d9f3f804.png)
