### ISSUE TITLE
Assign Social Worker to Need

### ISSUE THREAD

**Issue by nvick** [OfficeMomsandDads/scheduler#123]
User Story:

As a volunteer, I need to know which social worker is in charge of the case so that I know who to contact if I have any issues during my shift. 

Acceptance Criteria:

- [x] Someone creating a need can assign a social worker + social worker's contact information to the need from a drop-down list that only displays social workers associated with that office. 
- [x] Any user viewing the need could view the associated social worker + contact information
- [x] The social worker + contact info is editable in the "edit need" view

**Comment by joelmichael** [comment]
Just to clarify, we want to be able to edit and permanently alter contact information for social workers from the Edit Need view? And by contact information do we specifically mean phone number, or email address, or both?

**Comment by nvick** [comment]
It has been long enough; I don't have a clear picture of what I meant by editable. I believe what we want is the ability to re-assign a Need to a different social worker after it was created. The contact info, in this case, is phone number.

**Comment by benjaminwood** [comment]
From our call with Sarah:

Let's allow selecting one or more Child Welfare Workers. Also note the name change Social Worker -> Child Welfare Worker.
