### ISSUE TITLE
Setup scheduler:update_blockouts cron in staging/production

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#138]
This job needs to run daily or volunteer blockouts will not be projected.

https://github.com/OfficeMomsandDads/scheduler/blob/854eddee893453cf8c4e2b19b108a7a649421701/lib/tasks/scheduler.rake#L3-L14

I think we can use heroku scheduler for this.

**Comment by kyleboe** [comment]
Done 👍 
![image](https://user-images.githubusercontent.com/4054771/56835891-57a72e00-682a-11e9-9836-96335013290e.png)

**Comment by benjaminwood** [comment]
Nice!
