### ISSUE TITLE
Default to English

### ISSUE THREAD

**Issue by kyleboe** [OfficeMomsandDads/scheduler#145]
https://github.com/OfficeMomsandDads/scheduler/blob/302640a3854016a53aba7e775c5ed8cd11ef88e7/app/models/null_objects/null_language.rb#L5

Should be `'English'`

**Comment by kyleboe** [comment]
I think we should actually revisit this and ensure that this is truly defaulting and not using a NullObject pattern for the sake of reporting. See #190

**Comment by nvick** [comment]
Good catch.

**Comment by sarahwicks** [comment]
Hi, @kyleboe and @nvick - Is the issue here that the system is not defaulting to English if the user doesn't specify a language in the profile section? We're trying to triage, if you could put a summary of the issue here so we're sure we understand, that would be great. Thanks!

**Comment by benjaminwood** [comment]
I believe this issue is superseded by https://github.com/OfficeMomsandDads/scheduler/issues/190

@sarahwicks I'll follow up there with a better description.
