### ISSUE TITLE
Darcy can’t log in as Admin

### ISSUE THREAD

**Issue by DarcyBlank** [OfficeMomsandDads/scheduler#150]

**Comment by kyleboe** [comment]
I resent the admin invitation to you @DarcyBlank. Check your email 👍

**Comment by DarcyBlank** [comment]
Trying to log in as Admin to app.omd, and get this error message, but can’t find invite?

https://app.officemomsanddads.com/users/sign_in. Shoot I’m having a tough time moving the screen shot . . . Says I can’t sign in due to pending invitation.

**Comment by nvick** [comment]
It should be in your OMD email account. The logs on the server show it was deliver to the OMD email host at about 12:57.

**Comment by DarcyBlank** [comment]
Got it! Thx
