### ISSUE TITLE
Office locations — am I adding those? I think I said I would

### ISSUE THREAD

**Issue by DarcyBlank** [OfficeMomsandDads/scheduler#151]

**Comment by nvick** [comment]
Yes, offices will need to be added by an admin.

**Comment by DarcyBlank** [comment]
Thanks!

Darcy Blankenship
Volunteer Coordinator, Clark County

360.521.7138

> On Apr 25, 2019, at 5:47 PM, Nate Vick <notifications@github.com> wrote:
> 
> Yes, offices will need to be added by an admin.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
The information contained in this E-mail may be confidential and/or 
proprietary to Office Moms& Dads and/or its affiliates. The information 
transmitted herewith is intended only for use by the individual or entity 
to which it is addressed. If the reader of this message is not the intended 
recipient, you are hereby notified that any review, retransmission, 
dissemination, distribution, copying or other use of, or taking of any 
action in reliance upon this information is strictly prohibited. If you 
have received this communication in error, please contact the sender and 
delete the material from your computer.
