### ISSUE TITLE
[OMD Scheduler/production] Pundit::NotDefinedError: unable to find policy `NilClassPolicy` for `nil`

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#156]
## Backtrace

    line 7 of [PROJECT_ROOT]/app/controllers/shifts_controller.rb: index
    line 34 of [PROJECT_ROOT]/app/controllers/application_controller.rb: set_time_zone

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/59936/faults/48715883)

**Comment by benjaminwood** [comment]
I believe we should prevent a user from deleting the last shift of a need. Display an alert that says something to the effect of:

> Cannot remove the last shift from this need. Perhaps you mean to delete the need itself?

Feel free to reword, but that's the gist.

**Comment by kyleboe** [comment]
This is fixed and in production :+1:
