### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#159]
Can we get  a favicon created for the app?  I'm instructing folks to make it a shortcut on their favorites bar, but it looks a little naked.

Thanks!

**Comment by kyleboe** [comment]
Do you have the illustrator file for this icon?
![cropped-icon-omd](https://user-images.githubusercontent.com/4054771/56916124-0a66ce80-6a6d-11e9-9216-c210e11479b2.png)
I would like to remove the textured background for compression sake.

**Comment by kyleboe** [comment]
We will want to revisit this at some point so that we are not serving such a large image file. For now the favicon from the static site is in production 👍
