### ISSUE TITLE
Inviting Sarah Wicks

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#160]
Ben spoke with Sarah Wicks about being the contact person from OMD for all operational questions/feedback.  She is familiar with Github and is used to translating from human language for her job.  Can you please grant her access to Github?  caldwell@officemomsanddads.com

Thanks!

**Comment by nvick** [comment]
Awesome! I have sent the invite off to Sarah. If she has a Github account feel free to update the issue with her Github username and I will invite her that way.
