### ISSUE TITLE
Social Workers inviting Social Workers

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#164]
I'm sorry, I know this is changing what we had agreed upon, but it has become apparent that Social Workers need to invite other social workers during the roll out process.  Currently, they can invite volunteers, but not other social workers. Can you let me know when this has been adjusted so I can communicate it to the workers?  Thanks!!

**Comment by kyleboe** [comment]
This is verified working and in production :+1:
