### ISSUE TITLE
Volunteer scheduling

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#18]
As a social worker or volunteer coordinator, I want to manage needs.

- [x] I want to create new needs for my office up to two weeks in advance. I will provide relevant information including, day/time, duration, and the age range(s) of the kids as well as the language spoken.
- [x] I want needs to be to be automatically split into 1 hour `shifts`.
- [x] I want to manage the needs I have created, including canceling the entire need, canceling a single shift
- [x] As a volunteer coordinator, I want to directly assign a volunteer to a shift.
- [x] I want a notification to be sent to available volunteers when my need is created

**Comment by benjaminwood** [comment]
@SarahOMD should social workers be able to specify a specific day/time that they need a volunteer? Or, is the typical use-case that they're looking for a volunteer immediately?

Scheduling a volunteer for a later date/time would add some complexity, so current/immediate availability is preferable. Still, we can go either direction, let me know.

**Comment by benjaminwood** [comment]
From Sarah: 

> Age ranges should be 0-2, 3-5, 6-9, 10-12, and Teen.

**Comment by kyleboe** [comment]
@SarahOMD Currently, the way the system is built, the age range, preferred culture, preferred language, and number of children can be updated after a need has been created. When those need attributes are changed, do we want to re-notify the relevant volunteers of that change?

**Comment by kyleboe** [comment]
For posterity, we talked on the call today and *no* we don't want to re-notify volunteers about an update to a need if they have already been notified.
