### ISSUE TITLE
Need creation UI

### ISSUE THREAD

**Issue by sarahwicks** [OfficeMomsandDads/scheduler#180]
User Story:

As a Volunteer, I need to know more specific details about the children coming into care so that I can decide if I am willing and able to accept the request.

Dependencies:

- Blocks #181 

Acceptance Criteria:

- [ ] For each child coming into care, a user creating a need is able to specify the child's age, gender, and specific details once #181 is complete.

**Comment by haseebelahi** [comment]
Hey @sarahwicks, @benjaminwood ! I plan to pick this one up in the coming week!

**Comment by benjaminwood** [comment]
Great, thank you! Let me know if you have an questions I can answer. Also happy to collaborate, let me know!
