### ISSUE TITLE
State workers having trouble with access

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#182]
Hey guys.  A few state workers this morning reported trouble accessing the site.  I told them to use the browser Edge, but it didn't help.  They have alerted their IT dept, but I want to make sure it's nothing we can prevent on our end!  Thanks

**Comment by kyleboe** [comment]
What kind of trouble are they having? Like they can't access it at all? Does anything on the page load?

**Comment by SarahOMD** [comment]
Sounds like the page wouldn't even load.  It took an entire day, but the IT guy on site was able to work around their security.  I just don't understand why these offices aren't operating under universal IT security rules.  Seems like it should all be the same across the board!  

I just wanted to make sure it wasn't something on our end, since there were two offices having trouble yesterday.  Thanks!
