### ISSUE TITLE
"social worker" to Child Welfare Worker

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#183]
Can we change the role "social worker" to "Child Welfare Worker" to make it more universal for our clients?

**Comment by benjaminwood** [comment]
Yes, we can do that!

For implementation, let's change only the user facing display, keeping the role `social_worker` under the hood (it's shorter and still describes the role well).

**Comment by haseebelahi** [comment]
I can take on this one, but since the role is a simple string in the `users` table, how do we plan to keep both the under the hood name `social worker` & the display name `Child Welfare Worker`?

**Comment by Hkly** [comment]
Maybe add roles to the [locales](https://github.com/OfficeMomsandDads/scheduler/blob/master/config/locales/en.yml) with translations to the desired display name?

**Comment by benjaminwood** [comment]
@Hkly I like it!

What do you think @haseebelahi?

- [ ] Add role display name mapping to locales
- [ ] Add `User#role_display` (or similar) that returns the role from i18n.
- [ ] Use `User#role_display` everywhere we currently display the users role in the UI.
