### ISSUE TITLE
Editing User Profile

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#184]
As a user, I want to edit my medical information, criminal history, languages spoken, and/or cultural identity, etc. because I forgot to set it up initially.

 ---I have a child welfare worker who set up her profile with only her name, email, phone and time zone.  She would like to update the info, but is unable to get back in to the full form.

**Comment by kyleboe** [comment]
Correct me if I am wrong, but based on the initial spec, my understanding was that we only need said information for volunteers/volunteer coordinators that are going to be interacting with the children. This was based on the state being the ones responsible for that kind of information about child welfare workers. The ability to edit those attributes is enabled for volunteers and volunteer coordinators. 

If we need to add this for child welfare workers we can, I just want to clarify my understanding in the process. 

-------

Also, friendly reminder that for a user story, it is best to use the user role being described (e.g. "As a volunteer..." or "As a child welfare worker...") unless the feature/functionality applies directly to _all_ users regardless of role (admins included).

**Comment by SarahOMD** [comment]
Ok, yes @kyleboe you're right!  I forgot that we decided we didn't need that info from child welfare workers.  Disregard this issue!
