### ISSUE TITLE
Enhancement: Top-level shift information

### ISSUE THREAD

**Issue by sarahwicks** [OfficeMomsandDads/scheduler#187]
User Story:

As a social worker or volunteer coordinator, I need an easy way to see who has claimed a shift so that I know who to expect in the office.

Background:

Currently the only way to see who has claimed a shift is to edit the need. It would be much better if we could see who has claimed the shift without having to go into edit mode.

Acceptance Criteria:

- [x] The standard display shows who has claimed a shift (without having to enter edit mode).

**Comment by dinjas** [comment]
Is this one done?

**Comment by benjaminwood** [comment]
Yes, I believe it is. Thanks!
