### ISSUE TITLE
Enhancement: More detailed text message notifications

### ISSUE THREAD

**Issue by sarahwicks** [OfficeMomsandDads/scheduler#188]
User Story:

As a social worker, I need an easy way to see who is coming into the office so I don't have to complete unnecessary steps to discover this information.

Background:

Current Process to discover identify of volunteer(s) who have claimed shifts:
1. Volunteer claims shift
2. Social worker is notified via text message
3. Social worker logs in to app
4. Social worker clicks on need
5. Social worker clicks on "edit need"
6. Social worker can view identity of volunteer.

In order to streamline this process, please include the volunteer's name from his/her profile in the text message.

Sample Text Msg:

"Jane Doe has claimed a shift from 9 to 10 a.m."

Acceptance Criteria:

- [x] The volunteer's name is included in the text message sent to social workers.

**Comment by haseebelahi** [comment]
Hi @sarahwicks, @nvick! I'm trying to get involved and this looks like a good first issue for me which I can tackle, should I pick this one up?

**Comment by benjaminwood** [comment]
Hi @haseebelahi - great!

Yes, this is a good first issue to tackle. Let me know if you have questions!

**Comment by benjaminwood** [comment]
Great work @haseebelahi, thanks for the contribution!

This is on production & staging now. Can you verify behavior and close this issue if all is well?

**Comment by haseebelahi** [comment]
Thanks @benjaminwood, I'm not really sure though how to test this on staging since I don't have the credentials or anything. Can you help me in this regard? thanks.

**Comment by sarahwicks** [comment]
Thanks for your contribution, @haseebelahi! We really appreciate it. @benjaminwood, let me know if we can assist with testing in the stg environment. cc: @SarahOMD @DarcyBlank

**Comment by benjaminwood** [comment]
@haseebelahi my apologies! I meant to mention @sarahwicks in the second paragraph of my previous message.

@sarahwicks yes please! It'd be great if someone can confirm that they are now seeing the volunteer name in text messages.

**Comment by sarahwicks** [comment]
@benjaminwood - will do, thanks! Thanks again, @haseebelahi!

**Comment by sarahwicks** [comment]
We hear that this is working! Thank you, @haseebelahi, for your contribution!!!
