### ISSUE TITLE
Enhancement: Request Subscriptions

### ISSUE THREAD

**Issue by sarahwicks** [OfficeMomsandDads/scheduler#189]
As a Volunteer Coordinator/Social Worker/Hub Leader/Exec, I need the ability to subscribe to notifications I want to receive so I can remain informed.

Background:

Currently, only the person who enters the request receives notifications. Other social workers may want to be notified if a shift is claimed. Volunteer Coordinators may also want to be notified if shifts are requested or changed.

Acceptance Criteria:

- [ ] In the social worker or admin profile, users can select which notifications they'd like to receive, e.g., "I want to receive notifications only for requests I sent."; "I want to receive notifications for any requests sent for (multi-select menu of sites)."

OR

- [ ] In the request UI, the requester can multi-select users who will receive notifications for that specific request.

OR

Both

**Comment by joelmichael** [comment]
@benjaminwood I think we've already completed this one, too.

**Comment by benjaminwood** [comment]
Yep!
