### ISSUE TITLE
Volunteer shift accept/reject

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#19]
As a volunteer, I want to receive notification when a new need is created, so that I can respond.

- [x] I want to receive a text message with basic information about the need and a link to the need.
- [x] I want to receive a text message confirmation which includes date details about a shift I have accepted.
- [x] I want to see the status of the shifts (open/closed)
- [x] I want to receive a text message when a need is canceled
- [x] I want to receive a text message if my own shift is canceled

**Comment by benjaminwood** [comment]
@SarahOMD when a volunteer accepts an opportunity, how will other volunteers (who were also notified) know that the need has been filled?

**Comment by nvick** [comment]
@kyleboe when you have a moment will you look at the task list above to and if it is done close out this issue.

**Comment by kyleboe** [comment]
Because of the limitation issues raised in #104, I have crossed the notification when all shifts are taken off the list. We can revisit this in the future when we have means of circumventing said limitations.

**Comment by benjaminwood** [comment]
crossed the notification?

**Comment by kyleboe** [comment]
Updated comment for clarity
