### ISSUE TITLE
Question: Should everyone attached to an office receive all notifications?

### ISSUE THREAD

**Issue by DarcyBlank** [OfficeMomsandDads/scheduler#191]
"Anytime an OMD request is added or deleted, **all registered user** have been getting text messages. I don’t know if this was intended, but just want to let you know in case it needs to be corrected in the system."

I thought that the requestor and all volunteers for the time of the request would get the notifications, but not all of the social workers. We are asking the person making this comment to keep an eye on what she is seeing, but thought it worth adding to our list. Thanks.

https://mail.google.com/mail/u/1?ui=2&ik=eb0723d4b6&attid=0.1.2&permmsgid=msg-f:1632971594884324610&th=16a97b0381621d02&view=fimg&sz=s0-l75-ft&attbid=ANGjdJ8au6bI0DFgET-pxB3gMr9-uD4MZI-UZsRmmkPSTHnwyDbc0kwpC1YIx68UFJcISEGWDkdikbfnqv1cE9BMsru4ljjG_RukYEAz6tMGXbglOZ0nVioLySC5RMc&disp=emb

**Comment by benjaminwood** [comment]
Only `volunteers` & `coordinators` are intended to receive need notifications. I took a look at the code that filters this and it appears correct to me.

In order to investigate this further, we'll need more specific information regarding who received a notification that was not expected to.

If you feel this is no longer a concern, feel free to close.

**Comment by DarcyBlank** [comment]
The original comment came from the King West Office a couple weeks ago. It happened today with Vancouver Office Social Worker Krista Thompson today. I created a need yesterday, and was filling in volunteers to time slots. Krista texted to tell me she was received notifications. 
Image-1.jpg

**Comment by benjaminwood** [comment]
Thanks @DarcyBlank! I see text "Image-1.jpg" in your message. Was there supposed to be an image there? Can you find out exactly what the content of the message was that she received? We'll look into it!

**Comment by benjaminwood** [comment]
Actually, disregard that last message. We were able to look up exactly which messages she received by looking them up in twilio (the text message provider).

I had misspoken when I said 

> Only volunteers & coordinators are intended to receive need notifications.

What I meant to say was:

> Only volunteers & coordinators are intended to receive **new** need notifications.

Based on what I see below, it looks like she is receiving the messages that are intended, which are the ones that both a volunteer coordinator and social worker would receive. If you see messages below that you feel she should not receive, we can modify the behavior.

| From       | To         | Body                                                                                                                   | Status    | SentDate                | ApiVersion | NumSegments | ErrorCode | AccountSid                         | Sid                                | Direction    | Price    | PriceUnit |
|------------|------------|------------------------------------------------------------------------------------------------------------------------|-----------|-------------------------|------------|-------------|-----------|------------------------------------|------------------------------------|--------------|----------|-----------|
| 3607630663 | 3609073280 | A Volunteer has taken the shift Today from 02:00pm to 03:00pm. http://app.officemomsanddads.com/needs/77               | delivered | 2019-05-24 16:25:01 UTC |            | 1           | 0         | ACbadc3b417891ae87ae6115f4747e7d9d | SM8aec87db47c44f1fb575bb2d0177496e | outbound-api | -0.00562 | USD       |
| 3607630663 | 3609073280 | A Volunteer has taken the shift Today from 01:00pm to 02:00pm. http://app.officemomsanddads.com/needs/77               | delivered | 2019-05-24 16:24:46 UTC |            | 1           | 0         | ACbadc3b417891ae87ae6115f4747e7d9d | SM67e9d1cdd08745ec84095b0993fa4fb3 | outbound-api | -0.00562 | USD       |
| 3607630663 | 3609073280 | A Volunteer has taken the shift Today from 12:00pm to 01:00pm. http://app.officemomsanddads.com/needs/77               | delivered | 2019-05-24 16:24:33 UTC |            | 1           | 0         | ACbadc3b417891ae87ae6115f4747e7d9d | SMf983d152e29848b0b9c8ff0c34c6348a | outbound-api | -0.00562 | USD       |
| 3607630663 | 3609073280 | A need at Vancouver has been deleted.                                                                                  | delivered | 2019-05-22 16:16:07 UTC |            | 1           | 0         | ACbadc3b417891ae87ae6115f4747e7d9d | SM8efda7fef33c46dcb1efd0065f235f4c | outbound-api | -0.00562 | USD       |
| 3607630663 | 3609073280 | A Volunteer has unassigned themself from the 03:30pm to 05:00pm shift Today. http://app.officemomsanddads.com/needs/66 | delivered | 2019-05-21 19:35:16 UTC |            | 1           | 0         | ACbadc3b417891ae87ae6115f4747e7d9d | SMea521f96e3f9436ba508f8250f7a43ef | outbound-api | -0.00562 | USD       |
| 3607630663 | 3609073280 | A Volunteer has taken the shift Today from 03:30pm to 05:00pm. http://app.officemomsanddads.com/needs/66               | delivered | 2019-05-21 19:34:59 UTC |            | 1           | 0         | ACbadc3b417891ae87ae6115f4747e7d9d | SMb4707c1cffbb4da982aa9860f36263d6 | outbound-api | -0.00562 | USD       |
| 3607630663 | 3609073280 | You have taken the shift Today from 03:30pm to 05:00pm. http://app.officemomsanddads.com/needs/66                      | delivered | 2019-05-21 19:34:48 UTC |            | 1           | 0         | ACbadc3b417891ae87ae6115f4747e7d9d | SM0b9cfd9f03474db28ff63102fb28894a | outbound-api | -0.00562 | USD       |

**Comment by benjaminwood** [comment]
Krista Thompson received the notifications we would expect based on the rules of the system, I'm going to close this out. Feel free to open a new issue if you'd like the notification rules to change!
