### ISSUE TITLE
A lot of error messages

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#196]
I keep getting these emails, but usually for only user at a time.  This one was a lot.  Can you tell me what's going on??  I can forward you the email if it would help.

You are receiving this email because the following debugging events triggered one of your configured Alert Triggers.ErrorTime30005 - Unknown destination handset2019-05-15 20:20:47 UTC30005 - Unknown destination handset2019-05-15 20:20:45 UTC30005 - Unknown destination handset2019-05-15 20:20:42 UTC30005 - Unknown destination handset2019-05-15 20:20:36 UTC30005 - Unknown destination handset2019-05-15 20:20:35 UTC30005 - Unknown destination handset2019-05-15 20:20:33 UTC30005 - Unknown destination handset2019-05-15 20:17:52 UTC30005 - Unknown destination handset2019-05-15 20:17:51 UTC30005 - Unknown destination handset2019-05-15 20:17:50 UTC30005 - Unknown destination handset2019-05-15 14:36:37 UTC | Error | Time | 30005 - Unknown destination handset | 2019-05-15 20:20:47 UTC | 30005 - Unknown destination handset | 2019-05-15 20:20:45 UTC | 30005 - Unknown destination handset | 2019-05-15 20:20:42 UTC | 30005 - Unknown destination handset | 2019-05-15 20:20:36 UTC | 30005 - Unknown destination handset | 2019-05-15 20:20:35 UTC | 30005 - Unknown destination handset | 2019-05-15 20:20:33 UTC | 30005 - Unknown destination handset | 2019-05-15 20:17:52 UTC | 30005 - Unknown destination handset | 2019-05-15 20:17:51 UTC | 30005 - Unknown destination handset | 2019-05-15 20:17:50 UTC | 30005 - Unknown destination handset | 2019-05-15 14:36:37 UTC
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

30005 - Unknown destination handset | 2019-05-15 20:20:47 UTC
30005 - Unknown destination handset | 2019-05-15 20:20:45 UTC
30005 - Unknown destination handset | 2019-05-15 20:20:42 UTC
30005 - Unknown destination handset | 2019-05-15 20:20:36 UTC
30005 - Unknown destination handset | 2019-05-15 20:20:35 UTC
30005 - Unknown destination handset | 2019-05-15 20:20:33 UTC
30005 - Unknown destination handset | 2019-05-15 20:17:52 UTC
30005 - Unknown destination handset | 2019-05-15 20:17:51 UTC
30005 - Unknown destination handset | 2019-05-15 20:17:50 UTC
30005 - Unknown destination handset | 2019-05-15 14:36:37 UTC

**Comment by benjaminwood** [comment]
Is the email from twilio? I'm guessing the number isn't textable or it is blank/missing.

It may be related to this error (reported by honeybadger): https://app.honeybadger.io/projects/59936/faults/48746325#notice-summary

We've got a branch that refactors notification logic to ensure the above error does not happen: https://github.com/OfficeMomsandDads/scheduler/pull/117

@dinjas has been working on that off-and-on on Friday's.

**Comment by SarahOMD** [comment]
Yes, it was from Twilio, but I checked the numbers in our database, and they seem correct.  Could it be the cell service carrier?

**Comment by benjaminwood** [comment]
As discussed on our call earlier this week:

1. Sarah has unsubscribed from these notifications
2. Twillio indicates that the problem is that these phone numbers cannot receive text messages
3. The solution is to validate phone numbers upon signup/update. We've opened an issue for that here: https://github.com/OfficeMomsandDads/scheduler/issues/200

With that, I feel this issue can be closed!
