### ISSUE TITLE
Users receiving error message: "not authorized" to create need; text notifications failing to send

### ISSUE THREAD

**Issue by DarcyBlank** [OfficeMomsandDads/scheduler#197]
Got this message from Marleen Payment today: "I just tried to send my first need out through the app and it told me that I was not authorized to do that, so I had to send it through regular text. "

I (Darcy) also got a similar message today, but my Vancouver need did post. But there were no takers, so I'm wondering if maybe it didn't really go anywhere? Thanks.

**Comment by benjaminwood** [comment]
@DarcyBlank thanks for the report. If it happens again can you get a screenshot?

**Comment by DarcyBlank** [comment]
![image](https://user-images.githubusercontent.com/49794219/57975994-dc4d1e00-798a-11e9-8b75-dbeeb754851a.png)
[hint error message.docx](https://github.com/OfficeMomsandDads/scheduler/files/3194608/hint.error.message.docx)
[hint error message.docx](https://github.com/OfficeMomsandDads/scheduler/files/3194609/hint.error.message.docx)

We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

**Comment by DarcyBlank** [comment]
Sorry -- I'm back again. I got that message now when testing with a few of our volunteers, yet the need posted three times (oh, because I resubmitted the form; sorry).  I'm getting the message signed in as both Volunteer Coordinator Darcy and as Admin. Thanks again.

**Comment by nvick** [comment]
Thanks, @DarcyBlank. We will take a look at it. 

https://app.honeybadger.io/projects/59936/faults/49465294

**Comment by DarcyBlank** [comment]
Social worker, Krista Thompson, Vancouver office, received message on May 21 for a 1-hour shift starting at 3:30. No responses, as notification text was not sent. (She was using Chrome on her tablet.)

I received this message again today when creating a new request. Looks created, but texts do not go out to volunteers. Manually texted volunteers, "assigned" them to shifts -- they did receive text notification of assigned shifts. (Created with Chrome on iPad)

I did test again (looks created but no notification texts) and then deleted need; received text message that need was deleted. So that's good. (Created with Edge browser on PC)

**Comment by sarahwicks** [comment]
We've observed this bug for:
-Vancouver (Admin, social worker, volunteer coordinator)
-Tumwater

These sites are working fine:
-Boise
-Caldwell

**Comment by sarahwicks** [comment]
@DarcyBlank, I updated the title here to better represent the bug (since it's not constrained to a single user)

**Comment by benjaminwood** [comment]
I'm going to work on this today.

**Comment by benjaminwood** [comment]
I've gotten to the bottom of the error report that we received and it should be resolved now. Somehow a blockout was created where the start time was before the end time. We have a validation that should prevent this, so I'm going to follow up on that to ensure it is working.

By the way, I believe there are two distinct issues described here. One is the 'not authorized' issue, the other is the error which we received notification of (the part I fixed today).

If the not authorized error continues to occur, please open another issue and provide as much context as possible so we can track it down (it's harder to track down than an error).
