### ISSUE TITLE
User, Volunteer Susan Schroeder Block-out Dates -- July & August blocked out, but not by her

### ISSUE THREAD

**Issue by DarcyBlank** [OfficeMomsandDads/scheduler#199]
Volunter Susan Schroeder, reported the following on May 16:

"Looks like it’s letting me put in half days now. But it has me blocked out for all of July and August and I know I didn’t do that." Would you please check on what's happened? Thanks.

**Comment by sarahwicks** [comment]
@DarcyBlank, can you see if this is related to #171?

**Comment by benjaminwood** [comment]
I'm fairly confident this is user error. I'm closing the issue now, but please feel free to re-open if the issue turns out to be reproducible.
