### ISSUE TITLE
Share Brand colors

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#2]
@officemoms1 can you share the brand colors here so we can use them as we start building UI.

**Comment by officemoms1** [comment]
Gray - #404040
Teal - #2FCFD9
Purple - #881FBF

**Comment by officemoms1** [comment]
![screen shot 2018-11-09 at 11 19 31 am](https://user-images.githubusercontent.com/43186440/48283478-78610000-e411-11e8-9906-5b779cdbefe1.png)
Sign Up Button in the top right hand corner

**Comment by benjaminwood** [comment]
Great, thanks @officemoms1!
