### ISSUE TITLE
Layout/navigation

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#20]
Not sure what it should look like yet, lets discuss.

**Comment by kyleboe** [comment]
For posterity, We discussed referencing the planning center design as inspiration for layout/navigation.

**Comment by kyleboe** [comment]
Last item on the punchlist is mobile nav stuffs. Everything else is pretty much done.

**Comment by kyleboe** [comment]
Mobile nav is resolved and when #65 is merged we can close this issue out.
