### ISSUE TITLE
Phone Verification

### ISSUE THREAD

**Issue by nvick** [OfficeMomsandDads/scheduler#200]
As the system, we need to verify that the phone numbers being enter are sms capable so that we minimize the amount of sms sending errors and are able to communicate with our users.

- [x] a verification code is sent during account creation
- [x] once the phone number is verified as sms capable account is created
- [x] a new phone number is requested after X amount of time or retries

**Comment by joelmichael** [comment]
Should a phone number be verified after it's updated?

**Comment by benjaminwood** [comment]
Yes!

**Comment by joelmichael** [comment]
I assume we want to actually create a user record but just flag it as unverified. Which might require adding a scope to only select verified users throughout the code, possibly a default scope.

**Comment by joelmichael** [comment]
It also seems reasonable to me that if a phone number is updated, a user would lose its verified status until the new number is verified. Also I guess a default scope wouldn't be a good idea since all current accounts are going to start out unverified.

**Comment by joelmichael** [comment]
Should we grandfather in all current accounts as if they were verified? Or should we actually attempt to verify all of them

**Comment by benjaminwood** [comment]
Yeah, good point regarding the migration of existing users. Technically, the 'account' (`User`) is created when an invite is sent. The phone number verification step should come after the user accepts the invite and fills out the rest of their details.

So, if a user is signed in but has not verified their phone number, we should *always* redirect them to the phone number verification screen.

As for the migration, I think we should ask all users to verify their phone number (start them all `verified = false`). BUT, we shouldn't enforce numbers to be verified in order for text messages to be sent until the critical mass have verified their numbers (probably a few weeks, maybe more).

Make sense?

**Comment by joelmichael** [comment]
Alright, for now we'll leave off scoping only verified accounts anywhere, and just focus on collecting verifications. Then later we can add those scopes to appropriate places, until eventually all active users will be required to be verified, and maybe then it can be made into a default scope.

**Comment by nvick** [comment]
What if we did a rake task to validate numbers with Twilio for all current users? If we are sending SMS without issue to current then the number should not need to go through verification. 

We do have social workers and some volunteers that have put in an invalid number that should be forced to verify on the next login.

**Comment by joelmichael** [comment]
Can Twilio validate the phone numbers without actually sending an SMS? I'm a bit hesitant to send an unsolicited SMS to every user just to validate they received it. A more gradual collection of verifications might be preferable from their perspective

**Comment by benjaminwood** [comment]
Yeah, I too assumed we were talking about SMS verification where you enter the code you receive.

@nvick were you talking about verification where the user is not involved?

**Comment by nvick** [comment]
Let's do a short call to talk it out.
