### ISSUE TITLE
"Remember Me" in sign-up screen

### ISSUE THREAD

**Issue by sarahwicks** [OfficeMomsandDads/scheduler#211]
User Story:

As a [all roles], I need to indicate whether the OMD app should remember my credentials so I don't have to waste time logging in every time I access the app via a device I trust.

Acceptance Criteria:

- [ ] The sign-in screen for the app includes a check-box and "Remember Me," option, which will keep the user signed in for [TBD] time.

- [ ] The user only remains signed in on the specific device he/she indicated; if the user logs in via a different device, the "Remember Me" option is available for that device as well.

**Comment by sarahwicks** [comment]
@benjaminwood / @nvick - I'd like users to remain logged in as long as possible without putting OMD at risk. What's your recommendation? cc: @SarahOMD @DarcyBlank

**Comment by nvick** [comment]
Two weeks is the default and what I see as current best practice.

**Comment by sarahwicks** [comment]
Closing, this already exists! I don't know why I thought it didn't. @benjaminwood @nvick
