### ISSUE TITLE
Missing Office = skipped no. 12 on the list

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#213]
Today I tried to re-invite a social worker from the Lynnwood office, so I "destroyed" his previous invitation, and went back in to send the invite.  The Lynnwood office was missing from the dropdown menu, so I figured it "destroyed" the office in the process of destroying his profile invitation too.  

While re-creating the Lynnwood office in the Offices tab, I noticed that no. 12 is missing from the list, even though all offices are otherwise accounted for.  OMD has 24 offices, but with the addition of the Lynnwood office that I created today, the numbers are somehow off (skipping 12 and adding no. 25 to the end of the list).

**Comment by nvick** [comment]
@SarahOMD the ID is automatically assigned during creation of the office. If Lynnwood was deleted there is high likelihood it was ID=12. On creating the new office it used ID=25 which is the next available ID.

**Comment by SarahOMD** [comment]
Got it.  Looks like it's back on the drop down menu (See issue #214 ).  Thanks!

**Comment by kyleboe** [comment]
Also, we looked through the code and it did not destroy the office in the process of destroying the invite. Offices are not destroyed in any other way than manually deleting them in the admin interface. The Lynwood office had to have been manually deleted for it to go away.

**Comment by SarahOMD** [comment]
Yep.  I realize now what I did.... instead of destroying the user, I destroyed the office.  

I'm still worried about the drop down menu issue for #214
