### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#215]
The readme has great info about how to get a development environment setup, but is lacking just about everything else. I was thinking we should include:

### Non-technical
1. Short intro Office Moms and Dads (mission, vision, etc)
1. Short description of what purpose the app serves / short list of key features
1. Abridged roadmap (maybe this should link to a wiki page?)
1. Why get involved/help?
1. OMD contact information

### Technical
1. Overview of technologies employed (Ruby/Rails/Docker/JS/React/etc)
1. Getting started (the current dev setup information)
1. How to contribute (focus on process - issues, tests, PR's, etc)
1. Maintainer information (names, role, contact info?) 

### Other
1. Open source license information (MIT, I think)

**Comment by dinjas** [comment]
@benjaminwood is this one done?

**Comment by benjaminwood** [comment]
Yep, I'd say so!
