### ISSUE TITLE
Question: Can two different users have the same email address?

### ISSUE THREAD

**Issue by DarcyBlank** [OfficeMomsandDads/scheduler#216]

**Comment by dinjas** [comment]
Hi Darcy. Users can't have the same email. If they could, then the app wouldn't know which user to check the password against when the user is trying to sign in to the app. If you try to invite a user with an email that's already been taken, you should see an error like this:


<img width="637" alt="Screen Shot 2019-06-18 at 9 00 48 AM" src="https://user-images.githubusercontent.com/15596/59700136-9791ee00-91a7-11e9-870a-12c27e2f95b1.png">

**Comment by DarcyBlank** [comment]
Thanks. That’s what I expected but didn’t remember if anyone had tried. 

Darcy Blankenship
Volunteer Coordinator, Clark County

360.521.7138

> On Jun 18, 2019, at 9:01 AM, Jason Dinsmore <notifications@github.com> wrote:
> 
> Hi Darcy. Users can't have the same email. If they could, then the app wouldn't know which user to check the password against when the user is trying to sign in to the app. If you try to invite a user with an email that's already been taken, you should see an error like this:
> 
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
The information contained in this E-mail may be confidential and/or 
proprietary to Office Moms& Dads and/or its affiliates. The information 
transmitted herewith is intended only for use by the individual or entity 
to which it is addressed. If the reader of this message is not the intended 
recipient, you are hereby notified that any review, retransmission, 
dissemination, distribution, copying or other use of, or taking of any 
action in reliance upon this information is strictly prohibited. If you 
have received this communication in error, please contact the sender and 
delete the material from your computer.

**Comment by dinjas** [comment]
@DarcyBlank - I am going to go ahead and close this issue. Feel free to make another if you feel there is something that needs to be changed. Thanks!
