### ISSUE TITLE
Everett Office New Need not being texted out to Volunteers

### ISSUE THREAD

**Issue by DarcyBlank** [OfficeMomsandDads/scheduler#220]
VC created the need for Everett office (and could see it immediately), but a **text notification did not go out to the volunteers.** VC can manage the shifts.
The need is visible to the volunteers and they can claim shifts when they are notified outside of the app that the need exists.

This occurred for new needs for:
May 28.    10-12 (2hours)
June 18th. 9-10:30’ish (1hour and a half)
June 25th 10-12 (2hours) 

Refer to #197

**Comment by nvick** [comment]
@DarcyBlank thanks for the details. I’m to look into this over the holiday weekend.

**Comment by nvick** [comment]
@DarcyBlank I reviewed the logs in Twilio this morning for failed or undelivered SMS for the Everett office needs. The latest need had five users notified, and notified three out of the five for every need in the office. The Twilio logs show "delivered" for all of those users.

**Comment by DarcyBlank** [comment]
Thanks for such a quick response, Nate. I’ll ask her to let us know if it seems to continue. 

Darcy Blankenship
Volunteer Coordinator, Clark County

360.521.7138

> On Jul 5, 2019, at 8:00 AM, Nate Vick <notifications@github.com> wrote:
> 
> @DarcyBlank I reviewed the logs in Twilio this morning for failed or undelivered SMS for the Everett office needs. The latest need had five users notified, and notified three out of the five for every need in the office. The Twilio logs show "delivered" for all of those users.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 
The information contained in this E-mail may be confidential and/or 
proprietary to Office Moms& Dads and/or its affiliates. The information 
transmitted herewith is intended only for use by the individual or entity 
to which it is addressed. If the reader of this message is not the intended 
recipient, you are hereby notified that any review, retransmission, 
dissemination, distribution, copying or other use of, or taking of any 
action in reliance upon this information is strictly prohibited. If you 
have received this communication in error, please contact the sender and 
delete the material from your computer.
