### ISSUE TITLE
Shift Creation Feature Request: Increase Hours Toggle to 9 hrs

### ISSUE THREAD

**Issue by sarahwicks** [OfficeMomsandDads/scheduler#227]
User Story:

As someone who creates a need, I need the Expected Duration Slider bar in the "new need" UI to span a maximum of 9 hours so that I can schedule a full day of shifts.

Acceptance Criteria:

- [x] Expected Duration slider bar allows a selection of 9 hours

Background:

In the future, we may explore a more sophisticated solution in which the expected duration slider responds dynamically to the available hours in the start/end time tool.

**Comment by sarahwicks** [comment]
@nvick @benjaminwood @kyleboe Please add dev estimate, thanks!

**Comment by dinjas** [comment]
Is this one done?

**Comment by benjaminwood** [comment]
Yep!
