### ISSUE TITLE
Need Deletion/Creation Issue

### ISSUE THREAD

**Issue by nvick** [OfficeMomsandDads/scheduler#236]
We have been having trouble with the app. Many of my volunteers are still not getting the text, and this morning I sent out a request and then needed to change the time for going in, and it wouldn't let me edit the request. 

**I deleted it and created a new request and both of those ended up deleted. Tried to create another one and it's not showing up for anyone. I need a request from 12:00 to 5:00 for today, but we aren't able to respond to shifts.**

**Comment by benjaminwood** [comment]
@sarahwicks, @SarahOMD, @DarcyBlank

> We have been having trouble with the app. Many of my volunteers are still not getting the text

Can you provide phone numbers of affected users, please? Also, please provide specific examples of notifications they did not receive.

> and this morning I sent out a request and then needed to change the time for going in, and it wouldn't let me edit the request.
>
> I deleted it and created a new request and both of those ended up deleted.

As @nvick mentioned via email, it sounds like this user does not know how to add or remove shifts from an existing need. Did you communicate with this user/help them through the issue they were having?

> Tried to create another one and it's not showing up for anyone. I need a request from 12:00 to 5:00 for today, but we aren't able to respond to shifts.

Can you please provide steps to reproduce the problem? We'll be happy to investigate, but this report is not very actionable as-is.

**Comment by nvick** [comment]
On the phone numbers, please email those instead of posting them here in the issue.

**Comment by benjaminwood** [comment]
No response, closing.
