### ISSUE TITLE
Shift Editing/Deleting

### ISSUE THREAD

**Issue by nvick** [OfficeMomsandDads/scheduler#237]
I attempted to edit a need in the app today and when I was trying to delete a shift I got this message:

![image](https://user-images.githubusercontent.com/327614/62591227-c82b0580-b883-11e9-9457-dcfc5acc00f8.png)

**Comment by benjaminwood** [comment]
@sarahwicks, @SarahOMD, @DarcyBlank 

Are you able to reproduce this? Is it possible that the shift was already deleted by someone else when the effected user clicked 'delete'? If so, this is the message they should receive (expected as the shift no longer exists). 

As-is, this bug report is not very actionable for us to investigate assuming deleting shifts is not generally broken for all users (which to my knowledge it is not).

**Comment by benjaminwood** [comment]
Haven't had further reports of this, closing.
