### ISSUE TITLE
Reporting

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#27]
As an admin/Volunteer Coordinator:

- [x] I want reporting on volunteer hours by:
  - [x] individual
  - [x] office
  - [x] county
  - [x] state

- [x]  I want reporting on how many children are being served by:
  - [x] office
  - [x] county
  - [x] state

- [x] I want reporting on both volunteer & children demographics, so that we can recruit appropriate volunteer pools.

**Comment by kyleboe** [comment]
If we want to have graphs in the web app we could look at this tool https://www.reportskit.co/

**Comment by kyleboe** [comment]
Starting writing the queries to meet the spec. We can figure out how we want the data they produce to be output later.

**Comment by kyleboe** [comment]
This is now deployed to production 👍
![image](https://user-images.githubusercontent.com/4054771/58360301-e82e5980-7e3c-11e9-8a8c-01a73fcc76d6.png)
Navigate to the admin area and select Reports on the left. Clicking any of the links on that page will download a csv of the related data.

**Comment by kyleboe** [comment]
@SarahOMD & @DarcyBlank have you guys had the chance to test this out? Just wanted to make sure that everything is looking ok on your end and get feedback if anything isn’t working as expected.
