### ISSUE TITLE
Error when updating verified user without a phone number

### ISSUE THREAD

**Issue by FatherofDharma** [OfficeMomsandDads/scheduler#313]
Found at app-staging:

This issue appears to be related to verified accounts that have signed in. If you attempt to update without a phone number, it appears to render the new user form instead of the edit user form. You then have to go back to the user list and attempt to edit again.

This error appears to not get thrown if you edit a user without a phone number, if they haven't signed in successfully.

![Screenshot_2019-11-11 Edit NateSW Vick - Scheduler](https://user-images.githubusercontent.com/49597814/68612878-64137100-0472-11ea-9989-d37adb18adf6.png)

**Comment by FatherofDharma** [comment]
Verifed with another user:

![image](https://user-images.githubusercontent.com/49597814/68614559-fec17f00-0475-11ea-8923-5b90b4866a4a.png)

**Comment by FatherofDharma** [comment]
For the sake of thoroughness, I verified the issue running locally and while changing an email instead of phone.

![image](https://user-images.githubusercontent.com/49597814/68618001-426bb700-047d-11ea-8fcc-db6330b6a7fc.png)

**Comment by benjaminwood** [comment]
@FatherofDharma I see you moved this to "done" in the roadmap board. Is this issue not relevant in active admin? Or?

**Comment by benjaminwood** [comment]
@FatherofDharma I'm closing this now, but please let me know if you believe there is still a problem here.

**Comment by FatherofDharma** [comment]
@benjaminwood I apologize for not having seen this notification sooner. I believe the issue is resolved and will also be irrelevant if and when the active admin changes go through. Again, my apologies for the delay.
