### ISSUE TITLE
Allow User Account Deactivation/Deletion

### ISSUE THREAD

**Issue by nvick** [OfficeMomsandDads/scheduler#346]
Currently, if a user has been associated with a Need or Shift, their account cannot be removed from the system.

**Comment by zachhweed** [comment]
I'd gladly take this on. Are you all looking to allow for soft-deletion as well?

**Comment by benjaminwood** [comment]
Hi @zachhweed, great! Let's start with deactivation, which should prevent the user from logging in or receiving new sms notifications. It'd also be nice to indicate which users are deactivated in the admin interface!

**Comment by benjaminwood** [comment]
@zachhweed are you still interested in working on this? Let me know if I can help.

**Comment by zachhweed** [comment]
@benjaminwood yes, I definitely am! I stepped away following some env issues but just got those squared away. I'll have this out asap.

**Comment by benjaminwood** [comment]
Cool! Happy to collaborate if you run into anything else. Lemme know.
