### ISSUE TITLE
Twilio account is suspended?

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#362]
I received the following email from Twilio with regards to the OMD Twilio account.

Did anyone else receive this? I checked the account and on one screen is shows a negative credit balance. On another, it shows a positive credit balance. Possibly a bug?

Another client of Hint's received a similar email and is in the same situation, so it might be a wide spread problem that Twilio is having.

The big question is... is it actually affecting the delivery of text messages?

> Subject: "Your Twilio account is suspended and will continue to be charged"
> 
> Your Twilio Account (ACbadc3b417891ae87ae6115f4747e7d9d) balance is empty, so we've suspended your ability to send and receive phone calls and SMS messages. To ensure that you can use your Phone Numbers after you have reactivated your account, we do not automatically release your phone numbers. You will continue to be billed for the numbers while your account is suspended.
>
> 
> To reactivate your Twilio account, please visit our Billing page to recharge your account and restore service. You can avoid account suspension in the future by setting up auto-recharge for your account when it gets low.
> 
> 
> If you'd prefer not to be charged for your phone numbers going forward, please release any Twilio numbers you have in your main account or subaccounts.

**Comment by nvick** [comment]
It was a mistake on Twilio’s part. There were a number of NPOs effected.

**Comment by benjaminwood** [comment]
Oh great. Did they make an announcement?

**Comment by nvick** [comment]
No, I opened a support ticket when I received this morning.

**Comment by benjaminwood** [comment]
Oh, okay. I'll close this.
