### ISSUE TITLE
Bug report from Darcy

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#374]
Darcy Blankenship reports:

> Hi there. A Vancouver office has tried to create a need a couple times today and it is reportedly deleting each newly created need. It’s been a little crazy for our volunteers and frustrating for the social worker.

Not a lot of info to go on here, but let's investigate what recent changes might cause a newly created need to disappear from the list.

**Comment by joelmichael** [comment]
I was able to create a need in my dev environment, and it did show up in the list. However I have a theory that they might be using the new date filter on accident, thus filtering the new needs from the list. I'd be happy to talk to the bug reporter about it, or if they want to provide steps to reproduce then that will be good too.

**Comment by benjaminwood** [comment]
No further reports of this issue, closing it now.
