### ISSUE TITLE
Add date range to reports

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#409]
Currently, reporting returns information for 'all time'. We need to be able to set a start & end date range where applicable.

**Comment by rogeralexmiller** [comment]
Hi @benjaminwood, I'm interested in helping out with this project and am looking for a good first issue to work on. Based on this issue description, I'm assuming you're referring to the `/admin/reports` page, which is generated by the `app/admin/reports.rb` file. Is that correct? If so, would the scope of this issue involve just adding the back-end capability for these reports to get filtered by date-range, or would it also include the front-end portion?

**Comment by benjaminwood** [comment]
Hi @rogeralexmiller, great! We'd love your help. How'd you find this project?

Sorry this issue isn't spec'd out better. Your assessments are correct, that is the right file & route. Ideally, this issue would encompass both the backend and front end. Though, if you start with the backend and want somebody else to take the front end, I'm sure we could work that out!

Let me know if you have any other questions. It'd be nice if the reports page had a single set of date inputs (start & end), then, when a user selects a report, the result will be scoped by the dates selected on the page. The default dates should be the last 30 days, I think.

Note that I just merged https://github.com/OfficeMomsandDads/scheduler/pull/424. It makes changes to code surrounding reports, so make sure you pull master before digging in to avoid merge conflicts!

**Comment by rogeralexmiller** [comment]
@benjaminwood: sorry for delay on response. I found this project through a ruby meetup in Portland. I was asking the meetup founder Jonan about volunteer programming projects and he introduced me to Jason Dinsmore, who said this project might need some extra hands.

I've got a day job, but I'm gonna try to dive in and do some work after hours or on weekends.

I've been able to setup my environment ok, but one thing I'm missing I think are some of the env variables the readme mentioned are on 1Password. Could you share those with me? My email is rogeralexmiller@gmail.com.

**Comment by benjaminwood** [comment]
@rogeralexmiller awesome! Glad to hear it.

Hmm, that's a good point about the development key not being accessible to all. We'll work on a solution for that asap, thanks for pointing it out.

**Comment by benjaminwood** [comment]
@rogeralexmiller turns out the bit about the `.env` in 1Password can be disregarded. You should be able to run the app in development & test with we the default values in `env-example`. We've updated the readme to remove the reference to 1Password.
