### ISSUE TITLE
Horizontal Logo In Menu Bar

### ISSUE THREAD

**Issue by kyleboe** [OfficeMomsandDads/scheduler#45]
This is a low priority issue but the logo design doesn't quite work while horizontal. 
![omd-horiz-logo](https://user-images.githubusercontent.com/4054771/51499980-39d8b180-1d81-11e9-8a85-4bcc6c87afa2.png)

For now I will bump the logo in the header to 50px height and call it.

**Comment by benjaminwood** [comment]
I mean, it’s not great, but I’m not sure what else could be done with it short of changing it completely.

Do you have any specific concerns?

**Comment by kyleboe** [comment]
Got an updated logo back from teresa. Probably gonna run with this one. 👍

![omd-logo-horiz](https://user-images.githubusercontent.com/4054771/51875923-bb998380-231b-11e9-9422-51bbf291f3ea.png)

**Comment by kyleboe** [comment]
forgot about normal github theme 😅 
![image](https://user-images.githubusercontent.com/4054771/51875960-dc61d900-231b-11e9-8147-2ff05536365d.png)

**Comment by nvick** [comment]
I'm going to close this for now and we can revisit if needed.
