### ISSUE TITLE
Allow admins to msg all volunteers at once

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#468]
@SarahOMD wrote via email:

> Is there a way to communicate to all users via text using the scheduler?  Since things are changing so rapidly, this is really the best way to ensure that all volunteers are receiving the same message at the same time

**Comment by dinjas** [comment]
- [ ] Create Announcement model
  - message (string, not null)
  - author_id (integer, not null, fk on User table)
  - user_ids (bigint [], not null)
  - timestamps
- [ ] Add Rails validations to model
- [ ] Add method to model to send announcement
- [ ] Add spec(s) for model
- [ ] Add AnnouncementPolicy (for pundit)
- [ ] Add AnnouncementsController
  - [ ] Index
  - [ ] New
  - [ ] Create
  - [ ] Show
  I dont think we need edit/update as it doesn't really make sense to edit a message after it's been sent. IMO, destroy should not be implemented either
- [ ] Add specs for controller
- [ ] Add Announcement to ActiveAdmin
  - [ ] Add nav link
  - [ ] Index
  - [ ] New
  - [ ] Show
