### ISSUE TITLE
Make Nice Datepicker for Needs form

### ISSUE THREAD

**Issue by kyleboe** [OfficeMomsandDads/scheduler#54]
![image](https://user-images.githubusercontent.com/327614/53141962-ff606100-3546-11e9-9796-aecf60e7f4a9.png)
Replace with a React datepicker

**Comment by sarahwicks** [comment]
Can you add a non dev description to this ticket so we can prioritize? @benjaminwood @kyleboe

**Comment by dinjas** [comment]
Can this one be closed?

**Comment by benjaminwood** [comment]
Yes, it'd done!
