### ISSUE TITLE
Exit Survey

### ISSUE THREAD

**Issue by nvick** [OfficeMomsandDads/scheduler#570]
As OMD leadership, I want volunteers to be sent a link to a short exit survey 30 minutes after finishing a shift so that we can improve our systems and collect general data for reporting.

Acceptance Criteria:
- [ ] Creates an exit survey with a unique link/token
- [ ] Sends a message with a link to a volunteer's notification preference 30 minutes after completing all accepted shifts for a need
- [ ] Add report in admin for reviewing exit survey(need details from Sarah)

**Comment by benjaminwood** [comment]
@cidsinga I recall we had a meeting with Sarah where she provided details about the form itself. Do you have notes on that?  If so, could you share them here?

**Comment by cidsinga** [comment]
Sarah was going to get back to us with the actual questions etc for the exit survey, but never did, and I didn’t get far enough along to need to ask for them. So I don’t think the questions have ever been created.

Casey

**Comment by benjaminwood** [comment]
From Sarah via email:

> **Text message:**
> 
> > Thanks for taking a shift at the child welfare office today! We’d love to know how you’re feeling about it, or if there’s anything that needs our attention. Please take this one-minute survey.
> 
> 
> **Survey:**
> 
> > Did you have adequate supplies to care for the child(ren) during your time at the office? 
> > 
> > Y/N
> > 
> >   - If no, create a comment box (“what was missing or running low?”)
> 
> Did the assigned social worker respond to questions or concerns in a timely manner?
> 
> > Y/N
> > 
> >   - If no, create a comment box (“Tell us about that. Please include the social worker’s name so we can follow up.”)
> 
> Did the hours you signed up for match the hours you volunteered?
> 
> > Y/N
> > 
> > -If no, create a comment box (“How many hours did you volunteer today in total?”)
> 
> How are you feeling after your shift at the child welfare office? (check all that apply)
> 
> > * Happy
> > * Contented
> > * Excited
> > * Restless
> > * Sad
> > * Worried
> > * Angry
> >
> > Include a comment box if they want to elaborate
> 
> Your feedback is important to us, and we love hearing from our volunteers! Do you have any comments or kudos you’d like to pass along?
> 
> > Y/N (answer is optional)
> > Comment box
> 
> Any questions for your Volunteer Coordinator?
> 
> > Y/N
> > 
> > -If yes, create a comment box
