### ISSUE TITLE
Blockout calendar UI problem

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#59]
At desktop size, the date picker for the 'until' recurrence option is off screen. 

![image](https://user-images.githubusercontent.com/1232531/52511079-5e22f380-2bb3-11e9-9c42-ac61cdd33de9.png)

**Comment by benjaminwood** [comment]
Maybe not the best option but we could consider setting overflow: visible on .blockout-modal-content

![image](https://user-images.githubusercontent.com/1232531/52511205-d38ec400-2bb3-11e9-9dd6-bb4eb02e6898.png)

**Comment by nshoes** [comment]
Can the calendar just render to the right of the input?

**Comment by benjaminwood** [comment]
Yes, but we have to conditionally move it depending on responsive layout. I think this broken when @kyleboe fixed it on mobile.

**Comment by kyleboe** [comment]
Resolved with #64
