### ISSUE TITLE
User invitations

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#6]
As staff, I want to invite other staff and social workers, so that they can use the system.

**Comment by benjaminwood** [comment]
@SarahOMD regarding who invites who, I imagine it working this way:

1. Staff can invite anyone

**Comment by SarahOMD** [comment]
Correct!

**Comment by benjaminwood** [comment]
@SarahOMD I've invited you to the app as an admin. You should have received an email to set your password. Once you're in you can test the invite workflow for yourself. Let me know if you have any questions or if you run into any problems.

Also remember you can access the admin section at `/admin`. So, the URL would be http://omd-scheduler.herokuapp.com/admin

**Comment by benjaminwood** [comment]
Okay, I've got the permissions stuff implemented. I've also changed 'Coordinator' to 'Volunteer Coordinator'.

The basic invitation flow is complete and this issue has overlapping responsibility with #1. So, I'm going to close this one and track profile configuration as part of #1.
