### ISSUE TITLE
Volunteer schedule preferences

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#7]
As a volunteer, I want to put in my own availability/blockout dates, so I don’t get requests for dates I cannot volunteer.

**Comment by benjaminwood** [comment]
@SarahOMD I think we should model this after Planning Center Services blockout dates. https://pcoservices.zendesk.com/hc/en-us/articles/360002035974

What do you think? Any concerns with this approach?

I presume you have access to Services on Union Chapels account. I no longer have access to services, so I've created a new account/church to experiment and observe behavior. Let me know if you'd like access for testing purposes, I'll add you (cc @nvick).

**Comment by nvick** [comment]
This was my thinking as well.

**Comment by SarahOMD** [comment]
Me too!  I even love the pithy "excuses" it auto-generates when a user blocks out dates ;-)

**Comment by benjaminwood** [comment]
Nice, would be fun to work that feature in. :smile:

**Comment by benjaminwood** [comment]
While Planning Center's desktop blackout scheduling tool is very cool, we should keep our first iteration simple and implement something like what their mobile app provides. We'll need a UI more like this for mobile anyway, might as well share a simple interface for both mobile & desktop initially.

![image](https://user-images.githubusercontent.com/1232531/50751064-d4bb8280-11fc-11e9-92b1-2c92c41fa241.png)

One important factor in my mind is that we use the recurring options they provide which is the same on both desktop and mobile. There are 1k ways to allow users to input recurring details, but planning center really nailed it in my view.

If/when we implement a fancier rapid entry interface like planning center has on desktop, I think we'll want to build something around the React day picker: http://react-day-picker.js.org. Pretty sure it provides all the API we'd need to match Planning Center (drag to select multiple, click to select single).

**Comment by benjaminwood** [comment]
We're going to use the rrule standard for recurring events (see #22 for more discussion).

1. Rrule specification: https://icalendar.org/iCalendar-RFC-5545/3-8-5-3-recurrence-rule.html
1. Minimalist ruby gem for expanding RRULEs: [ruby-rrule](https://github.com/square/ruby-rrule)
1. javascript library for rrule: https://github.com/jakubroztocil/rrule

* Users will create block-out dates one at a time.
* Interface will be similar to Planning center's mobile UX
* Recurrence information will be persisted as rrule strings.
* Recurring events will be handled lazily. `rrule.js` will be used to display recurring events on the front end. `ruby-rrule` will be used on the backend to expand rrules. We will only store recurring events two weeks into the future because that is as far as needs can be scheduled.

**Comment by benjaminwood** [comment]
I'm going to start working on this now, starting with the back-end.

**Comment by kyleboe** [comment]
This seems to be all taken care of and in master. Closing for now.
