### ISSUE TITLE
Preferred Language should be English (not none)

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#71]
@SarahOMD this is something you mentioned in our meeting today. However, I'm having second thoughts about this. When no preferred language is selected for a need (shown as 'none' below), notifications will be sent to all volunteers regardless of their spoken language. If it defaults to English, only English speaking volunteers will be notified.

So the question is, do you want to have the option of not specifying a preferred language?

If instead you'd prefer all needs to specify a language, then we'll change wording from 'preferred language' to 'language' and make it a required field on all needs.

![image](https://user-images.githubusercontent.com/1232531/53130104-353d1f80-351e-11e9-90d5-a4526ac5a1db.png)

**Comment by SarahOMD** [comment]
Or could we just change the word "none" to "not specified"?

**Comment by benjaminwood** [comment]
Yes!

**Comment by benjaminwood** [comment]
This has been fixed!
