### ISSUE TITLE
Better need duration UX

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#72]
We store need duration in minutes, however the need form should should display duration in hours. A dropdown for hours and a dropdown for minutes (in 15 minute increments) may be the simplest way to accomplish this. Of course, we'll have to translate that to minutes server side.

Alternatively we could use JS client side to translate into minutes.

![image](https://user-images.githubusercontent.com/1232531/53130494-44709d00-351f-11e9-9c02-86378e6a3e96.png)

**Comment by habibalamin** [comment]
@jordanluce and I are planning to work on this right now.

**Comment by benjaminwood** [comment]
Cool, let me know if you have questions.

**Comment by habibalamin** [comment]
@benjaminwood sorry for notifying you so late, but we've had to drop this due to time constraints and competing priorities.

**Comment by benjaminwood** [comment]
All good, thanks for following up.

**Comment by kyleboe** [comment]
Resolved by #135
