### ISSUE TITLE
Inconsistencies with adjusting shift requests

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#77]
Comment from Darcy...
This original request was for 2:00, then I added an earlier shift. I can manage the 1:00 hour, but the "Need" in gray-scale and "Start Time" in Details still show 2:00. Suggest that those areas change to match changed request.
Also, the details do not show the ages of kids.
![image](https://user-images.githubusercontent.com/43186440/53370015-6c864480-3901-11e9-9349-f47e33a03836.png)

**Comment by benjaminwood** [comment]
This has been resolved!
