### ISSUE TITLE
New User, Phone Number

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#78]
Comment from Darcy...
does phone number format matter? I did not receive any text messages from the site, even with 3 admin/volunteers having my number for the testing. (And I know my number will text to itself!) This is hindering my ability to robustly test some of the functionality.

**Comment by nvick** [comment]
I’m looking into message sending on the staging server. It currently works in development but not on the server. I’ll update here when I have more info.

**Comment by nvick** [comment]
@SarahOMD this should now be working. I created a new need and assigned Darcy to a shift after I fixed the issue.

**Comment by benjaminwood** [comment]
@SarahOMD I'm going to close this issue now. Feel free to re-open or open a new issue if any other messaging problems arise.
