### ISSUE TITLE
New User (all)

### ISSUE THREAD

**Issue by SarahOMD** [OfficeMomsandDads/scheduler#79]
-- could required information be marked with an asterisk, or could we add statement to say, "all info is required"?

**Comment by dinjas** [comment]
@SarahOMD Is this in reference to the page for inviting a new user:

<img width="1258" alt="screen shot 2019-03-01 at 12 24 15 pm" src="https://user-images.githubusercontent.com/15596/53664310-03fad880-3c1d-11e9-9165-09f6c4a4b6e2.png">


Or this page, where the user accepts the invitation and creates their account?

<img width="1238" alt="screen shot 2019-03-01 at 12 24 02 pm" src="https://user-images.githubusercontent.com/15596/53664336-15dc7b80-3c1d-11e9-843c-6bac13a25b07.png">

Thanks!

**Comment by SarahOMD** [comment]
Thanks for the question!  I believe it was for the page where the user creates a new account.

**Comment by dinjas** [comment]
Excellent, thank you!

**Comment by benjaminwood** [comment]
Fixed! Thanks @dinjas
