### ISSUE TITLE
Record volunteer race & spoken language

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#8]
As a social worker, I want to know what race and/or culture  the volunteers identify as, as well as spoken language, so we can find the best possible match with the kids entering care.

**Comment by SarahOMD** [comment]
I'm picturing a drop down menu for race/ethnicity featuring the most common 20 (or so).  For the language, I'm picturing either a drop down or fill-in-the-blank for "first language" and "second language".

**Comment by benjaminwood** [comment]
Cool, thanks!

We'll choose drop-downs with pre-defined options whenever possible for the sake of data normalization. This is important/useful when it comes to reporting as allowing users to enter information fill-in-the-blank style often results in duplicates with various kinds of misspellings or uses of punctuation, etc.

Let's establish what those 20 (or so) most common ethnicities are and then off 'other' as an alternative?

Can we do something similar for spoken language? Could we offer a list of languages that'd cover 99% of volunteers with 'other' as an option for edge-cases?

If it turns out we need more flexibility we can discuss other options. Let us know what you think @SarahOMD

**Comment by benjaminwood** [comment]
Per our phone conversation today we will go with a drop-down list of most common options in both cases.

@SarahOMD can you provide a list for each?

**Comment by SarahOMD** [comment]
Top 25 Spoken Languages in Washington State (per https://statisticalatlas.com/state/Washington/Languages)
Spanish
Mandarine
Cantonese
Vietnamese
Russian
Tagalog
Filipino
Korean
Amharic 
Somali
Austronesian
Ilocano
Samoan
Hawaiian
German
Ukrainian
Romanian
Japanese
Hindi
French
Khmer
Arabic
Punjabi
Thai
Lao

**Comment by SarahOMD** [comment]
The racial thing was harder to google.  Feel free to give input!  

White/Caucasian
Black/African American
Hispanic
Asian
Native Hawaiian/Pacific Islander
Eastern European
Indian
American Indian/Alaska Native

**Comment by benjaminwood** [comment]
Great, thanks @SarahOMD.

Some development notes:

- [ ] Add primary & secondary language to User and add it to the signup form as required fields (but not for social workers)
- [ ] Add race to User and add it to the signup form as a required field (but not for social workers)

@SarahOMD should we require this information be collected in for both volunteers and volunteer coordinators? Seems like it'd be useful information in both cases.

**Comment by kyleboe** [comment]
This is fully implemented. Closing 👍
