### ISSUE TITLE
Allow volunteers to specify child age ranges

### ISSUE THREAD

**Issue by benjaminwood** [OfficeMomsandDads/scheduler#9]
As a volunteer, I want to set my preference regarding the age range of kids I work with, so that I can have a more positive experience.

**Comment by SarahOMD** [comment]
Age ranges should be 0-2, 3-5, 6-9, 10-12,  and Teen.  Users should be able to select as many as they'd like.

**Comment by benjaminwood** [comment]
Development notes:

- [ ] Create new model `AgeRange` with attributes `min` & `max`.
- [ ] Make has and belongs to many association between User and AgeRange
- [ ] Allow Volunteers to select multiple age ranges when signing up and updating their profile
- [ ] Add admin dashboard for AgeRange

Note, if a volunteer has selected no age ranges, we assume they are open to opportunities with children of any age.
